version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  dev-net:
